# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, null=True, verbose_name='username')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('workphone', models.CharField(max_length=200, null=True)),
                ('homephone', models.CharField(max_length=200, null=True)),
                ('mobilephone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=200, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('changeuserinfo', models.CharField(max_length=128, null=True)),
                ('portalloginpassword', models.CharField(max_length=128, null=True)),
                ('enableportallogin', models.IntegerField(default=0)),
                ('creationdate', models.DateTimeField(auto_now=True)),
                ('creationby', models.TextField(default=django.utils.timezone.now, max_length=200)),
                ('updatedate', models.DateTimeField(null=True, verbose_name='update date')),
                ('updateby', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'verbose_name': 'userinfo',
            },
        ),
    ]
